Repository time-loop/clickup-projen, pull requests merged in 2023-03, with the labels that each got.

#123 chore(deps): update all non-major dependencies
  package.json
  yarn.lock
Labels: auto-approve

#126 chore(deps): update all non-major dependencies
  API.md
  package.json
  yarn.lock
Labels: auto-approve

#130 chore(deps): update all non-major dependencies
  package.json
  yarn.lock
Labels: auto-approve, renovate

#133 chore(deps): update all non-major dependencies
  package.json
  yarn.lock
Labels: auto-approve, renovate

#134 feat(infra): updating GHToken in renovate workflows [CLK-230021]
  .github/workflows/add-to-project.yml
  .github/workflows/renovate.yml
  src/add-to-project.ts
  src/renovate-workflow.ts
  test/__snapshots__/add-to-project.test.ts.snap
  test/__snapshots__/renovate-workflow.test.ts.snap
Labels: renovate

#135 chore(deps): update all non-major dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve, renovate

#137 chore(deps): update all non-major dependencies
  .eslintrc.json
  API.md
  package.json
  yarn.lock
Labels: auto-approve, renovate
